# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: ikesmith # jekyll-seo-tag > Owners twitter username
author: Isaac Smith # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Isaac Smith # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/ikesmith
    - https://www.facebook.com/ikesmith
    - https://github.com/isaacsmith

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: US/Eastern # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Blog # Needed for Siteleaf
    output: true
    description: "Writings on various topics" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Isaac Smith" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/wordmark.png" # Site logo, also used in jekyll-seo-tag
description: "My personal website and blog." # Site description and default description, also used in jekyll-seo-tag
url: "https://isaacsmith.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/isaacsmith/isaacsmith.github.io"
email: "ikesmith@gmail..com"
# disqus: "" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Projects: /projects/
  Blog: /blog/
  Categories: /categories/
  Search: /search/

navigation_footer:
  Alembic theme by David Darnes: https://alembic.darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/ikesmith
  Facebook: https://www.facebook.com/ikesmith
  LinkedIn: https://www.linkedin.com/in/isaacsmith
  Instagram: https://www.instagram.com/catsashimi
  Reddit: https://www.reddit.com/user/catsashimi
  GitHub: https://github.com/isaacsmith
  link: https://keybase.io/isaacsmith
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  Facebook: "#3B5998"
  Email: ""
